# This is a basic workflow to help you get started with Actions

name: CI-CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Autenticando o usuário no DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: Buildando e fazendo Push no DockerHub
        uses: docker/build-push-action@v3.1.1
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            maxxsantos/kube-news:latest
            maxxsantos/kube-news:${{github.run_number}}
            
  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - uses: actions/checkout@v3
      - name: Definindo o kube_config
        uses: Azure/k8s-set-context@v3.0
        with:
          method: kuberconfig
          kubeconfig: ${{secrets.K8S_CONFIG}}
      - name: Deploy do Cluster Kubernetes
        uses: Azure/k8s-deploy@v4.3
        with:
          images: maxxsantos/kube-news:${{github.run_number}}
          manifests: |
            k8s/deployment.yaml
